spring.application.name=springboot_data_jpa1
server.port=${PORT:8080}


spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
